const API_URL = "https://script.google.com/macros/s/AKfycbwt1E1CC6EDlvwmblrzM6vtK4WmYCrmpIhj_SV7NUvMmcsNweZXcr0E4M1X83dvsE7WlQ/exec";
const APP_VERSION = "27";
function appInstallId_(){var k="oddsklubben-install-id",v=localStorage.getItem(k);if(!v){v="ok-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,10);localStorage.setItem(k,v)}return v}
function logApp_(eventName,page,detail){if(!API_URL)return;try{fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({type:"app_log",event:eventName,page:page||"",installation:appInstallId_(),version:APP_VERSION,detail:detail||""})}).catch(function(){})}catch(e){}}

const players={Pingvinus:"🐧 Pingvinus",King:"👑 King",Gorilla:"🦍 Gorilla",Kaninus:"🐰 Kaninus",Kardinalus:"🙏 Kardinalus"};
let program=[
{w:43,r:"Supercup",m:["Kardinalus – King"],toto:["Pingvinus","Gorilla","Kaninus"]},
{w:44,r:"Runde 1",m:["Kardinalus – Kaninus","Gorilla – King"],free:"Pingvinus"},
{w:45,r:"Runde 2",m:["Kardinalus – Pingvinus","Kaninus – Gorilla"],free:"King"},
{w:46,r:"Runde 3 · Julecup 1/4",m:["King – Pingvinus","Kardinalus – Gorilla"],free:"Kaninus"},
{w:47,r:"Pokal · indledende · Julecup 2/4",m:["TBD – TBD"]},
{w:48,r:"Runde 4 · Julecup 3/4",m:["Gorilla – Pingvinus","King – Kaninus"],free:"Kardinalus"},
{w:49,r:"Runde 5 · Julecup 4/4",m:["Pingvinus – Kaninus","Kardinalus – King"],free:"Gorilla"},
{w:50,r:"Runde 6",m:["Kaninus – Kardinalus","King – Gorilla"],free:"Pingvinus"},
{w:51,r:"JULEFERIE",m:[]},{w:52,r:"JULEFERIE",m:[]},{w:1,r:"JULEFERIE",m:[]},
{w:2,r:"Runde 7",m:["Pingvinus – Kardinalus","Gorilla – Kaninus"],free:"King"},
{w:3,r:"Pokal · semifinaler",m:["TBD – TBD","TBD – TBD"]},
{w:4,r:"Runde 8",m:["Pingvinus – King","Gorilla – Kardinalus"],free:"Kaninus"},
{w:5,r:"Fri Odds",m:[],allFree:true},{w:6,r:"Runde 9",m:["Pingvinus – Gorilla","Kaninus – King"],free:"Kardinalus"},
{w:7,r:"Fri Odds",m:[],allFree:true},{w:8,r:"Pokalfinale",m:["TBD – TBD"]},{w:9,r:"Fri Odds",m:[],allFree:true},
{w:10,r:"Runde 10",m:["Kaninus – Pingvinus","King – Kardinalus"],free:"Gorilla"},{w:11,r:"Fri Odds",m:[],allFree:true},{w:12,r:"Fri Odds · sæsonafslutning",m:[],allFree:true}];
let pos=initialPosition();
let savedEntries=[];
function isoWeek(d=new Date()){const x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));const y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return Math.ceil((((x-y)/86400000)+1)/7)}
function initialPosition(){const now=new Date(),w=isoWeek(now),y=now.getFullYear();const i=program.findIndex(x=>x.w===w);if(i>=0 && (y===2026||y===2027))return i;return 0}
function names(match){return match.split(" – ").filter(n=>players[n]).map(n=>players[n])}
function moneyField(name){return `<div class="player"><label>${players[name]||name}</label><input data-kind="money" data-player="${name}" inputmode="decimal" placeholder="Kr" aria-label="Gevinst ${name}"></div>`}
function card(match,i){const ns=match.split(" – ").filter(n=>players[n]);return `<section class="card ${match.includes("TBD")?"cup":""}" data-match="${match}"><div class="tag">Kamp ${i+1}</div><div class="match">${match}</div>${ns.map(moneyField).join("")}<div class="result"><label>Resultat</label><input data-kind="result" inputmode="text" autocapitalize="off" autocomplete="off" placeholder="fx 2-1" aria-label="Resultat"></div></section>`}
function render(){const x=program[pos];document.getElementById("week").textContent=x.w;document.getElementById("round").textContent=x.r;document.getElementById("subtitle").textContent="Sæson 2026/27";document.getElementById("cards").innerHTML=x.m.length?x.m.map(card).join(""):`<div class="empty">${x.r.includes("FERIE")?"🎄 Juleferie":"🍺 Ingen faste kampe denne uge"}</div>`;if(x.free)document.getElementById("cards").innerHTML+=`<section class="card" data-match="Fri Odds"><div class="tag">Fri Odds</div><div class="match">${players[x.free]}</div>${moneyField(x.free)}</section>`;if(x.allFree)document.getElementById("cards").innerHTML=`<section class="card" data-match="Alle Fri odds"><div class="tag">Fri Odds · alle</div><div class="match">Hele klubben</div>${Object.keys(players).map(moneyField).join("")}</section>`;if(x.toto)document.getElementById("cards").innerHTML+=`<section class="card" data-match="Toto Cup"><div class="tag">Toto Cup · Fri Odds</div><div class="match">De tre øvrige spillere</div>${x.toto.map(moneyField).join("")}</section>`;document.getElementById("save").style.display=x.r.includes("FERIE")?"none":"block";document.getElementById("notice").textContent="";if(!restoreSaved_(x))restoreDraft_(x.w)}
document.getElementById("prev").onclick=()=>{pos=(pos-1+program.length)%program.length;render()};document.getElementById("next").onclick=()=>{pos=(pos+1)%program.length;render()};
function parseMoney(v){if(!v.trim())return null;const n=Number(v.trim().replace(/\s/g,"").replace(",", "."));return Number.isFinite(n)&&n>=0?n:null}
function validResult(v){return /^\d+\s*[-–]\s*\d+$/.test(v.trim())}
function validate(){const x=program[pos],inputs=[...document.getElementById("cards").querySelectorAll("input")],errors=[];inputs.forEach(el=>el.classList.remove("bad"));inputs.forEach(el=>{const isResult=el.dataset.kind==="result",value=el.value.trim();if(!value)return;const ok=isResult?validResult(value):parseMoney(value)!==null;if(!ok){el.classList.add("bad");errors.push(el)}});if(x.m.some(m=>m.includes("TBD"))){document.getElementById("notice").textContent="Pokalkampen afventer lodtrækning.";return false}if(errors.length){document.getElementById("notice").textContent="Tjek de markerede felter.";errors[0].focus();return false}const data=summary();if(!data.entries.some(function(e){return e.money!==null||e.result})){document.getElementById("notice").textContent="Indtast mindst ét beløb eller resultat før du gemmer.";return false}return true}
function restoreSaved_(x){var rows=savedEntries.filter(function(e){return Number(e.week)===Number(x.w)&&e.round===x.r});if(!rows.length)return false;document.getElementById("cards").querySelectorAll(".card[data-match]").forEach(function(card){var match=card.dataset.match;card.querySelectorAll('[data-kind="money"]').forEach(function(el){var e=rows.find(function(v){return v.match===match&&v.player===el.dataset.player});if(e&&e.money!=="")el.value=String(e.money).replace(".",",")});var re=card.querySelector('[data-kind="result"]');if(re){var e=rows.find(function(v){return v.match===match&&v.result});if(e)re.value=e.result}});return true}
function restoreDraft_(w){try{const d=JSON.parse(localStorage.getItem("oddsklubben-draft-"+w)||"null");if(!d||!Array.isArray(d.entries))return;document.getElementById("cards").querySelectorAll(".card[data-match]").forEach(card=>{const match=card.dataset.match;card.querySelectorAll('[data-kind="money"]').forEach(el=>{const e=d.entries.find(x=>x.match===match&&x.player===el.dataset.player);if(e&&e.money!==null)el.value=String(e.money).replace(".",",")});const re=card.querySelector('[data-kind="result"]');if(re){const e=d.entries.find(x=>x.match===match&&x.result);if(e)re.value=e.result}})}catch(_){}}
function summary(){const x=program[pos],entries=[];document.getElementById("cards").querySelectorAll(".card[data-match]").forEach(card=>{const match=card.dataset.match,resultEl=card.querySelector('[data-kind="result"]'),result=resultEl?resultEl.value.trim():"";card.querySelectorAll('[data-kind="money"]').forEach(el=>entries.push({match,player:el.dataset.player,money:parseMoney(el.value),result}))});return {week:x.w,round:x.r,entries}}
document.getElementById("save").onclick=()=>{if(!validate())return;const data=summary();document.getElementById("notice").innerHTML=`<div class="confirm"><strong>Klar til at gemme uge ${data.week}</strong><span>Kontrollér oplysningerne og tryk Bekræft.</span><button id="confirmSave">Bekræft og gem</button><button id="cancelSave" class="secondary">Ret oplysninger</button></div>`;document.getElementById("cancelSave").onclick=()=>document.getElementById("notice").textContent="";document.getElementById("confirmSave").onclick=()=>{localStorage.setItem("oddsklubben-draft-"+data.week,JSON.stringify(data));const btn=document.getElementById("confirmSave");btn.disabled=true;btn.textContent="Gemmer…";if(!API_URL){document.getElementById("notice").innerHTML='<div class="success">✓ Gemt som lokal kladde.<br><small>Backend er endnu ikke deployet.</small></div>';return}fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(data)}).then(function(res){return res.json()}).then(function(out){if(!out.ok)throw new Error(out.error||"Ukendt fejl");document.getElementById("notice").innerHTML=`<div class="success">✓ ${out.status==="written"?"Gemt i Google Sheet":"Test godkendt (dry-run)"}.<br><small>Uge ${data.week} · ${data.round}</small></div>`}).catch(function(err){document.getElementById("notice").innerHTML=`<div class="error">Kunne ikke gemme: ${String(err.message||err)}<br><small>Din lokale kladde er bevaret.</small></div>`})}};render();
fetch(API_URL).then(function(res){return res.json()}).then(function(out){if(out && out.ok && Array.isArray(out.program) && out.program.length){program=out.program;savedEntries=Array.isArray(out.saved)?out.saved:[];pos=initialPosition();render();if(window.renderSeasonProgram)window.renderSeasonProgram()}}).catch(function(){});
logApp_("app_open","forside","");
function programKind_(x){var r=String(x.r||"").toLowerCase();if(r.indexOf("pokal")>=0)return"cup";if(r.indexOf("runde")===0)return"league";if(r.indexOf("supercup")>=0||r.indexOf("toto")>=0||r.indexOf("julecup")>=0)return"special";return"other"}
function prettyMatch_(m){return String(m||"").replace("Kardinalus","🙏 Kardinalus").replace("Pingvinus","🐧 Pingvinus").replace("Kaninus","🐰 Kaninus").replace("Gorilla","🦍 Gorilla").replace("King","👑 King")}
function programCard_(x,i,current){var holiday=String(x.r||"").indexOf("JULEFERIE")>=0;var julecup=(String(x.r||"")+" "+String(x.note||"")).toLowerCase().indexOf("julecup")>=0;var roundLabel=(julecup?"🎄 ":"")+x.r;var t='<article class="program-week '+(i===current?"current ":"")+(holiday?"holiday ":"")+'" data-program-kind="'+programKind_(x)+'"><div class="program-week-head"><b>UGE '+x.w+'</b><span>'+roundLabel+'</span></div>';if(holiday)return t+'<div class="program-holiday">🎄 Juleferie</div></article>';if(x.m&&x.m.length){x.m.forEach(function(m){t+='<div class="program-match">'+(String(m).indexOf("TBD")>=0?'🏆 <strong>Modstandere afgøres ved lodtrækning</strong>':'<strong>'+prettyMatch_(m)+'</strong>')+'</div>'})}if(x.toto)t+='<div class="program-note">🎲 Toto Cup · '+x.toto.map(function(n){return players[n]||n}).join(" · ")+'</div>';if(x.allFree)t+='<div class="program-note">🎯 Fri Odds · hele klubben</div>';else if(x.free)t+='<div class="program-note">🎯 Fri Odds · '+(players[x.free]||x.free)+'</div>';if(julecup){var jc=(String(x.r||'')+' · '+String(x.note||'')).match(/Julecup[^·]*/i);t+='<div class="program-badge">🎄 '+(jc?jc[0].trim():'Julecup')+'</div>'}if(x.w===47)t+='<div class="program-note">2 spiller pokal · de øvrige 3 har Fri Odds</div>';if(x.w===3)t+='<div class="program-note">4 semifinalister · den øvrige spiller har Fri Odds</div>';if(x.w===8)t+='<div class="program-note">2 finalister · de øvrige 3 har Fri Odds</div>';return t+'</article>'}
window.renderSeasonProgram=function(){var wrap=document.getElementById("programTimeline"),hero=document.getElementById("programHero");if(!wrap||!hero)return;var current=initialPosition(),x=program[current];hero.innerHTML='<div><small>NÆSTE / AKTUELLE UGE</small><strong>Uge '+x.w+' · '+x.r+'</strong><span>'+(x.m&&x.m.length?x.m.map(prettyMatch_).join(" · "):x.r)+'</span></div>';function draw(filter){wrap.innerHTML=program.map(function(v,i){return programCard_(v,i,current)}).join("");Array.prototype.forEach.call(wrap.children,function(el){el.style.display=filter==="all"||el.getAttribute("data-program-kind")===filter?"block":"none"})}draw("all");document.querySelectorAll(".program-tab").forEach(function(btn){btn.onclick=function(){document.querySelectorAll(".program-tab").forEach(function(b){b.className="program-tab"});btn.className="program-tab active";draw(btn.getAttribute("data-program-filter"))}})};

var TIPS_URL="data/latest-tips.json";
var bettingTips={"updated":"2026-10-03 13:51 UTC","model_80kr_portfolio":{"budget_kr":80,"bets":[{"type":"single","stake_kr":40,"combined_probability":0.7684,"legs":[{"date":"2026-10-10","match":"FC Barcelona vs Getafe CF","selection":"FC Barcelona","probability":0.7684}]},{"type":"single","stake_kr":40,"combined_probability":0.7349,"legs":[{"date":"2026-10-10","match":"FC Internazionale Milano vs Parma Calcio 1913","selection":"FC Internazionale Milano","probability":0.7349}]}]},"smart_double":null,"smart_triple":{"combined_probability":0.3846,"legs":[{"role":"best_available","date":"2026-10-10","match":"FC Barcelona vs Getafe CF","selection":"FC Barcelona","probability":0.7684},{"role":"best_available","date":"2026-10-10","match":"FC Internazionale Milano vs Parma Calcio 1913","selection":"FC Internazionale Milano","probability":0.7349},{"role":"best_available","date":"2026-10-09","match":"Borussia Dortmund vs SV Werder Bremen","selection":"Borussia Dortmund","probability":0.681}]},"favorites":[{"date":"2026-10-10","match":"FC Barcelona vs Getafe CF","selection":"FC Barcelona","probability":0.7684},{"date":"2026-10-10","match":"FC Internazionale Milano vs Parma Calcio 1913","selection":"FC Internazionale Milano","probability":0.7349},{"date":"2026-10-09","match":"Borussia Dortmund vs SV Werder Bremen","selection":"Borussia Dortmund","probability":0.681}],"upsets":[{"date":"2026-10-10","match":"AFC Ajax vs NEC","selection":"NEC","probability":0.369,"uncertain":true},{"date":"2026-10-10","match":"Chelsea vs Bournemouth","selection":"Chelsea","probability":0.3665,"uncertain":true},{"date":"2026-10-10","match":"FC Lorient vs Paris FC","selection":"Paris FC","probability":0.3645,"uncertain":true}],"bold_upsets":[{"date":"2026-10-10","match":"1. FC Union Berlin vs SV 07 Elversberg","selection":"1. FC Union Berlin","probability":0.3427,"favorite_probability":0.4331,"tier":"bold"},{"date":"2026-10-10","match":"Swansea City AFC vs Norwich City FC","selection":"Norwich City FC","probability":0.3154,"favorite_probability":0.4323,"tier":"bold"},{"date":"2026-10-10","match":"Aston Villa vs Brentford","selection":"Brentford","probability":0.3078,"favorite_probability":0.4465,"tier":"bold"}]};
function pctTip_(p){return (Number(p)*100).toFixed(1).replace(".",",")+"%"}
function shortDate_(d){var a=String(d||"").split("-");return a.length===3?Number(a[2])+"/"+Number(a[1]):d}
function tipExplain_(x){var e=x.explanation;if(!e)return "";return '<details class="tip-explain"><summary>Hvorfor tror Bot’en på den?</summary><p>'+e.summary+'</p><div class="tip-explain-stats"><span>Forventede mål <b>'+Number(e.home_expected_goals).toFixed(2).replace(".",",")+' – '+Number(e.away_expected_goals).toFixed(2).replace(".",",")+'</b></span><span>Angrebsstyrke H/U <b>'+Number(e.home_attack_strength).toFixed(2).replace(".",",")+' / '+Number(e.away_attack_strength).toFixed(2).replace(".",",")+'</b></span><span>Forsvarsstyrke H/U <b>'+Number(e.home_defence_strength).toFixed(2).replace(".",",")+' / '+Number(e.away_defence_strength).toFixed(2).replace(".",",")+'</b></span></div></details>'}
function tipRows_(items,kind){return items.map(function(x,i){var doubt=x.uncertain?'<span class="tip-doubt">Bot’en er lidt i tvivl om det her · bedste tilgængelige bud</span>':'';return '<article class="tip-card '+kind+'"><div class="tip-rank">'+(i+1)+'</div><div class="tip-copy"><small>'+shortDate_(x.date)+'</small><strong>'+x.match.replace(" vs "," – ")+'</strong><span>'+x.selection+doubt+'</span>'+tipExplain_(x)+'</div><b>'+pctTip_(x.probability)+'</b></article>'}).join("")}
function tripleRole_(r){return r==="solid"?"Solid":r==="value"?"Værdi-signal":r==="best_available"?"Bedste tilgængelige":"Lille fidus"}
function paintSmartTriple_(){var el=document.getElementById("smartTriple"),t=bettingTips.smart_triple,d=bettingTips.smart_double,combo=t&&t.legs&&t.legs.length?t:d;if(!el)return;if(!combo||!combo.legs||!combo.legs.length){el.innerHTML='<p class="tips-empty">Ingen Smart Triple eller Smart Double i den aktuelle analyse.</p>';return}var title=t?"Smart Triple":"Smart Double";el.innerHTML='<div class="smart-combo-label">'+title+'</div><div class="smart-triple-card">'+combo.legs.map(function(x){return '<div class="triple-leg"><small>'+tripleRole_(x.role)+' · '+shortDate_(x.date)+'</small><strong>'+x.selection+'</strong><span>'+x.match.replace(" vs "," – ")+' · '+pctTip_(x.probability)+'</span></div>'}).join("")+'<div class="triple-total"><span>Samlet modelchance</span><b>'+pctTip_(combo.combined_probability)+'</b></div></div>'}
function paintPortfolio80_(){var el=document.getElementById("portfolio80"),p=bettingTips.model_80kr_portfolio;if(!el)return;if(!p||!p.bets||!p.bets.length){el.innerHTML='<p class="tips-empty">Intet 80 kr-forslag i den aktuelle analyse.</p>';return}el.innerHTML='<div class="portfolio-card">'+p.bets.map(function(b,i){var legs=b.legs.map(function(x){return '<span>'+x.selection+' · '+pctTip_(x.probability)+'</span><small>'+x.match.replace(" vs "," – ")+'</small>'}).join("");return '<div class="portfolio-bet"><div class="portfolio-stake"><b>'+b.stake_kr+' kr</b><span>'+(b.type==="double"?"Double":"Single")+'</span></div><div class="portfolio-legs">'+legs+'</div></div>'}).join("")+'<div class="portfolio-total"><span>Samlet indsats</span><b>'+p.budget_kr+' kr</b></div></div>'}
function paintBettingTips_(){paintPortfolio80_();paintSmartTriple_();var f=document.getElementById("favoriteTips"),u=document.getElementById("upsetTips"),b=document.getElementById("boldUpsetTips");if(f)f.innerHTML=bettingTips.favorites.length?tipRows_(bettingTips.favorites,"favorite"):'<p class="tips-empty">Ingen favoritsignaler i den aktuelle analyse.</p>';if(u)u.innerHTML=bettingTips.upsets.length?tipRows_(bettingTips.upsets,"upset"):'<p class="tips-empty">Ingen upset-signaler i den aktuelle analyse.</p>';if(b)b.innerHTML=bettingTips.bold_upsets&&bettingTips.bold_upsets.length?tipRows_(bettingTips.bold_upsets,"bold-upset"):'<p class="tips-empty">Ingen helt frække bud i den aktuelle analyse.</p>'}
window.renderBettingTips=function(){paintBettingTips_();fetch(TIPS_URL+"?t="+Date.now(),{cache:"no-store"}).then(function(r){if(!r.ok)throw new Error("feed");return r.json()}).then(function(data){bettingTips=data||bettingTips;paintBettingTips_()}).catch(function(){});logApp_("view","spilforslag","live feed")}

var BOT_BET_URL="data/bot-bets.json";
var botBetFallback={"name":"Bot'ens Bet","currency":"fiktive kr","bookmaker":"Bot’ens egne sandsynligheder med 90% tilbagebetaling","weeks":[{"coupon_date":"2026-10-03","model_updated":"2026-10-03 14:02 UTC","stake_kr":80,"rtp":0.9,"status":"open","return_kr":null,"profit_kr":null,"bets":[{"type":"single","stake_kr":40,"fake_odds":1.17,"legs":[{"date":"2026-10-10","match":"FC Barcelona vs Getafe CF","selection":"FC Barcelona","probability":0.7684,"fake_odds":1.17}],"result":"pending","return_kr":null},{"type":"single","stake_kr":40,"fake_odds":1.22,"legs":[{"date":"2026-10-10","match":"FC Internazionale Milano vs Parma Calcio 1913","selection":"FC Internazionale Milano","probability":0.7349,"fake_odds":1.22}],"result":"pending","return_kr":null}]}],"totals":{"settled_weeks":0,"stake_kr":0,"return_kr":0,"profit_kr":0,"return_pct":null},"updated":"2026-10-03 14:02 UTC"};
function botMoney_(n){return Number(n||0).toFixed(2).replace(".",",")+" kr"}
function botBetCards_(week){return week.bets.map(function(b,i){var state=b.result==="won"?"🟢 Vundet":b.result==="lost"?"🔴 Tabt":"⏳ Afventer resultat";var ret=b.return_kr===null||typeof b.return_kr==="undefined"?"":'<span class="botbet-return">Retur '+botMoney_(b.return_kr)+'</span>';return '<article class="botbet-bet '+(b.result||"pending")+'"><div class="botbet-bet-top"><b>Bet '+(i+1)+' · '+b.stake_kr+' kr</b><span>Fiktivt odds '+Number(b.fake_odds).toFixed(2).replace(".",",")+'</span></div>'+b.legs.map(function(x){return '<div class="botbet-leg"><strong>'+x.selection+'</strong><span>'+x.match.replace(" vs "," – ")+' · '+pctTip_(x.probability)+' · odds '+Number(x.fake_odds).toFixed(2).replace(".",",")+'</span></div>'}).join("")+'<div class="botbet-result"><strong>'+state+'</strong>'+ret+'</div></article>'}).join("")}
function botMood_(current,t){var mode=current&&current.risk_mode;var profit=Number(t&&t.profit_kr||0);if(!mode){mode=profit>=80?"protect":profit<=-240?"high":profit<=-80?"attack":"normal"}var moods={protect:{icon:"😌",title:"Bot’en er kølig",text:"Saldoen er solidt i plus. Bot’en beskytter føringen og går efter stærkere modelvalg."},normal:{icon:"🤖",title:"Bot’en er fokuseret",text:"Saldoen er omkring neutral. Bot’en følger sin normale 80 kr-strategi."},attack:{icon:"😤",title:"Bot’en er på jagt",text:"Saldoen er i minus. Bot’en accepterer mere risiko for at forsøge at hente underskuddet."},high:{icon:"😈",title:"Bot’en går til stålet",text:"Saldoen er markant i minus. Bot’en vælger sin højeste risiko blandt de aktuelle modelsignaler."}};return moods[mode]||moods.normal}
function paintBotBet_(data){var el=document.getElementById("botBetContent");if(!el)return;var weeks=data&&data.weeks?data.weeks:[],current=weeks.length?weeks[weeks.length-1]:null,t=data&&data.totals?data.totals:{};var mood=botMood_(current,t);var moodHtml='<section class="botbet-mood"><span class="botbet-mood-icon">'+mood.icon+'</span><div><small>BOT’ENS HUMØR</small><strong>'+mood.title+'</strong><p>'+mood.text+'</p></div></section>';var summary='<section class="botbet-score"><div><small>INDSAT</small><strong>'+botMoney_(t.stake_kr)+'</strong></div><div><small>RETUR</small><strong>'+botMoney_(t.return_kr)+'</strong></div><div><small>SALDO</small><strong>'+botMoney_(t.profit_kr)+'</strong></div></section>';if(!current){el.innerHTML='<section class="botbet-hero"><small>FØRSTE KUPON</small><strong>Bot’en gør klar 🤖</strong><span>Næste søndag morgen låses 80 fiktive kr på 2–4 modelspil.</span></section>'+moodHtml+summary;return}var history=weeks.slice(0,-1).reverse();var historyHtml=history.length?'<section class="botbet-history"><h2>Tidligere kuponer</h2><p>Bot’ens låste væddemål uge for uge.</p>'+history.map(function(w){return '<section class="botbet-week"><div class="botbet-week-head"><strong>'+w.coupon_date+'</strong><span>'+botMoney_(w.stake_kr)+' indsat · '+(w.status==="settled"?"afgjort":"afventer")+'</span></div>'+botBetCards_(w)+'</section>'}).join("")+'</section>':'<section class="botbet-history-empty">Historikken kommer her efter professorens første afsluttede uge.</section>';el.innerHTML='<section class="botbet-hero"><small>AKTUEL KUPON · '+current.coupon_date+'</small><strong>Bot’ens 80 kr</strong><span>Fiktiv bookmaker · 90% tilbagebetaling</span></section>'+moodHtml+botBetCards_(current)+summary+historyHtml}
window.renderBotBet=function(){paintBotBet_(botBetFallback);fetch(BOT_BET_URL+"?t="+Date.now(),{cache:"no-store"}).then(function(r){if(!r.ok)throw new Error("botbet");return r.json()}).then(function(data){paintBotBet_(data)}).catch(function(){})}
