const API_URL = localStorage.getItem("oddsklubben-api-url") || "https://script.google.com/macros/s/AKfycbwt1E1CC6EDlvwmblrzM6vtK4WmYCrmpIhj_SV7NUvMmcsNweZXcr0E4M1X83dvsE7WlQ/exec";
const players={Pingvinus:"🐧 Pingvinus",King:"👑 King",Gorilla:"🦍 Gorilla",Kaninus:"🐰 Kaninus",Kardinalus:"🙏 Kardinalus"};
const program=[
{w:43,r:"Supercup",m:["Kardinalus – King"],note:"Toto Cup: Pingvinus · Gorilla · Kaninus"},
{w:44,r:"Runde 1",m:["Kardinalus – Kaninus","Gorilla – King"],free:"Pingvinus"},
{w:45,r:"Runde 2",m:["Kardinalus – Pingvinus","Kaninus – Gorilla"],free:"King"},
{w:46,r:"Runde 3 · Julecup 1/4",m:["King – Pingvinus","Kardinalus – Gorilla"],free:"Kaninus"},
{w:47,r:"Pokal · indledende · Julecup 2/4",m:["TBD – TBD"]},
{w:48,r:"Runde 4 · Julecup 3/4",m:["Gorilla – Pingvinus","King – Kaninus"],free:"Kardinalus"},
{w:49,r:"Runde 5 · Julecup 4/4",m:["Pingvinus – Kaninus","Kardinalus – King"],free:"Gorilla"},
{w:50,r:"Runde 6",m:["Kaninus – Kardinalus","King – Gorilla"],free:"Pingvinus"},
{w:51,r:"JULEFERIE",m:[]},{w:52,r:"JULEFERIE",m:[]},{w:1,r:"JULEFERIE",m:[]},
{w:2,r:"Runde 7",m:["Pingvinus – Kardinalus","Gorilla – Kaninus"],free:"King"},
{w:3,r:"Pokal · semifinaler",m:["TBD – TBD","TBD – TBD"]},
{w:4,r:"Runde 8",m:["Pingvinus – King","Gorilla – Kardinalus"],free:"Kaninus"},
{w:5,r:"Fri Odds",m:[],allFree:true},{w:6,r:"Runde 9",m:["Pingvinus – Gorilla","Kaninus – King"],free:"Kardinalus"},
{w:7,r:"Fri Odds",m:[],allFree:true},{w:8,r:"Pokalfinale",m:["TBD – TBD"]},{w:9,r:"Fri Odds",m:[],allFree:true},
{w:10,r:"Runde 10",m:["Kaninus – Pingvinus","King – Kardinalus"],free:"Gorilla"},{w:11,r:"Fri Odds",m:[],allFree:true},{w:12,r:"Fri Odds · sæsonafslutning",m:[],allFree:true}];
let pos=0;
function names(match){return match.split(" – ").filter(n=>players[n]).map(n=>players[n])}
function moneyField(name){return `<div class="player"><label>${players[name]||name}</label><input data-kind="money" data-player="${name}" inputmode="decimal" placeholder="Kr" aria-label="Gevinst ${name}"></div>`}
function card(match,i){const ns=match.split(" – ").filter(n=>players[n]);return `<section class="card ${match.includes("TBD")?"cup":""}" data-match="${match}"><div class="tag">Kamp ${i+1}</div><div class="match">${match}</div>${ns.map(moneyField).join("")}<div class="result"><label>Resultat</label><input data-kind="result" inputmode="numeric" placeholder="fx 2-1" aria-label="Resultat"></div></section>`}
function render(){const x=program[pos];week.textContent=x.w;round.textContent=x.r;subtitle.textContent="Sæson 2026/27";cards.innerHTML=x.m.length?x.m.map(card).join(""):`<div class="empty">${x.r.includes("FERIE")?"🎄 Juleferie":"🍺 Ingen faste kampe denne uge"}</div>`;if(x.free)cards.innerHTML+=`<section class="card" data-match="Fri Odds">${`<div class="tag">Fri Odds</div><div class="match">${players[x.free]}</div>${moneyField(x.free)}</section>`};if(x.allFree)cards.innerHTML=`<section class="card" data-match="Alle Fri odds"><div class="tag">Fri Odds · alle</div><div class="match">Hele klubben</div>${Object.keys(players).map(moneyField).join("")}</section>`;if(x.note)cards.innerHTML+=`<section class="card"><div class="tag">Toto Cup</div><div class="match">${x.note.replace("Toto Cup: ","")}</div><p>Alle tre har Fri Odds.</p></section>`;save.style.display=x.r.includes("FERIE")?"none":"block";notice.textContent=""}
prev.onclick=()=>{pos=(pos-1+program.length)%program.length;render()};next.onclick=()=>{pos=(pos+1)%program.length;render()};
function parseMoney(v){if(!v.trim())return null;const n=Number(v.trim().replace(/\s/g,"").replace(",", "."));return Number.isFinite(n)&&n>=0?n:null}
function validResult(v){return /^\d+\s*[-–]\s*\d+$/.test(v.trim())}
function validate(){const x=program[pos],inputs=[...cards.querySelectorAll("input")],errors=[];inputs.forEach(el=>el.classList.remove("bad"));inputs.forEach(el=>{const isResult=el.dataset.kind==="result";const ok=isResult?validResult(el.value):parseMoney(el.value)!==null;if(!ok){el.classList.add("bad");errors.push(el)}});if(x.m.some(m=>m.includes("TBD"))){notice.textContent="Pokalkampen afventer lodtrækning.";return false}if(errors.length){notice.textContent="Tjek de markerede felter.";errors[0].focus();return false}return true}
function summary(){const x=program[pos],entries=[];cards.querySelectorAll(".card[data-match]").forEach(card=>{const match=card.dataset.match,result=card.querySelector('[data-kind="result"]')?.value.trim()||"";card.querySelectorAll('[data-kind="money"]').forEach(el=>entries.push({match,player:el.dataset.player,money:parseMoney(el.value),result}))});return {week:x.w,round:x.r,entries}}
save.onclick=()=>{if(!validate())return;const data=summary();notice.innerHTML=`<div class="confirm"><strong>Klar til at gemme uge ${data.week}</strong><span>Kontrollér oplysningerne og tryk Bekræft.</span><button id="confirmSave">Bekræft og gem</button><button id="cancelSave" class="secondary">Ret oplysninger</button></div>`;document.getElementById("cancelSave").onclick=()=>notice.textContent="";document.getElementById("confirmSave").onclick=async()=>{localStorage.setItem("oddsklubben-draft-"+data.week,JSON.stringify(data));const btn=document.getElementById("confirmSave");btn.disabled=true;btn.textContent="Gemmer…";if(!API_URL){notice.innerHTML='<div class="success">✓ Gemt som lokal kladde.<br><small>Backend er endnu ikke deployet.</small></div>';return}try{const res=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(data)});const out=await res.json();if(!out.ok)throw new Error(out.error||"Ukendt fejl");notice.innerHTML=`<div class="success">✓ ${out.status==="written"?"Gemt i Google Sheet":"Test godkendt (dry-run)"}.<br><small>Uge ${data.week} · ${data.round}</small></div>`}catch(err){notice.innerHTML=`<div class="error">Kunne ikke gemme: ${String(err.message||err)}<br><small>Din lokale kladde er bevaret.</small></div>`}}};render();