const API_URL = "https://script.google.com/macros/s/AKfycbwt1E1CC6EDlvwmblrzM6vtK4WmYCrmpIhj_SV7NUvMmcsNweZXcr0E4M1X83dvsE7WlQ/exec";
const players={Pingvinus:"🐧 Pingvinus",King:"👑 King",Gorilla:"🦍 Gorilla",Kaninus:"🐰 Kaninus",Kardinalus:"🙏 Kardinalus"};
let program=[
{w:43,r:"Supercup",m:["Kardinalus – King"],toto:["Pingvinus","Gorilla","Kaninus"]},
{w:44,r:"Runde 1",m:["Kardinalus – Kaninus","Gorilla – King"],free:"Pingvinus"},
{w:45,r:"Runde 2",m:["Kardinalus – Pingvinus","Kaninus – Gorilla"],free:"King"},
{w:46,r:"Runde 3 · Julecup 1/4",m:["King – Pingvinus","Kardinalus – Gorilla"],free:"Kaninus"},
{w:47,r:"Pokal · indledende · Julecup 2/4",m:["TBD – TBD"]},
{w:48,r:"Runde 4 · Julecup 3/4",m:["Gorilla – Pingvinus","King – Kaninus"],free:"Kardinalus"},
{w:49,r:"Runde 5 · Julecup 4/4",m:["Pingvinus – Kaninus","Kardinalus – King"],free:"Gorilla"},
{w:50,r:"Runde 6",m:["Kaninus – Kardinalus","King – Gorilla"],free:"Pingvinus"},
{w:51,r:"JULEFERIE",m:[]},{w:52,r:"JULEFERIE",m:[]},{w:1,r:"JULEFERIE",m:[]},
{w:2,r:"Runde 7",m:["Pingvinus – Kardinalus","Gorilla – Kaninus"],free:"King"},
{w:3,r:"Pokal · semifinaler",m:["TBD – TBD","TBD – TBD"]},
{w:4,r:"Runde 8",m:["Pingvinus – King","Gorilla – Kardinalus"],free:"Kaninus"},
{w:5,r:"Fri Odds",m:[],allFree:true},{w:6,r:"Runde 9",m:["Pingvinus – Gorilla","Kaninus – King"],free:"Kardinalus"},
{w:7,r:"Fri Odds",m:[],allFree:true},{w:8,r:"Pokalfinale",m:["TBD – TBD"]},{w:9,r:"Fri Odds",m:[],allFree:true},
{w:10,r:"Runde 10",m:["Kaninus – Pingvinus","King – Kardinalus"],free:"Gorilla"},{w:11,r:"Fri Odds",m:[],allFree:true},{w:12,r:"Fri Odds · sæsonafslutning",m:[],allFree:true}];
let pos=initialPosition();
let savedEntries=[];
function isoWeek(d=new Date()){const x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));const y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return Math.ceil((((x-y)/86400000)+1)/7)}
function initialPosition(){const now=new Date(),w=isoWeek(now),y=now.getFullYear();const i=program.findIndex(x=>x.w===w);if(i>=0 && (y===2026||y===2027))return i;return 0}
function names(match){return match.split(" – ").filter(n=>players[n]).map(n=>players[n])}
function moneyField(name){return `<div class="player"><label>${players[name]||name}</label><input data-kind="money" data-player="${name}" inputmode="decimal" placeholder="Kr" aria-label="Gevinst ${name}"></div>`}
function card(match,i){const ns=match.split(" – ").filter(n=>players[n]);return `<section class="card ${match.includes("TBD")?"cup":""}" data-match="${match}"><div class="tag">Kamp ${i+1}</div><div class="match">${match}</div>${ns.map(moneyField).join("")}<div class="result"><label>Resultat</label><input data-kind="result" inputmode="text" autocapitalize="off" autocomplete="off" placeholder="fx 2-1" aria-label="Resultat"></div></section>`}
function render(){const x=program[pos];document.getElementById("week").textContent=x.w;document.getElementById("round").textContent=x.r;document.getElementById("subtitle").textContent="Sæson 2026/27";document.getElementById("cards").innerHTML=x.m.length?x.m.map(card).join(""):`<div class="empty">${x.r.includes("FERIE")?"🎄 Juleferie":"🍺 Ingen faste kampe denne uge"}</div>`;if(x.free)document.getElementById("cards").innerHTML+=`<section class="card" data-match="Fri Odds"><div class="tag">Fri Odds</div><div class="match">${players[x.free]}</div>${moneyField(x.free)}</section>`;if(x.allFree)document.getElementById("cards").innerHTML=`<section class="card" data-match="Alle Fri odds"><div class="tag">Fri Odds · alle</div><div class="match">Hele klubben</div>${Object.keys(players).map(moneyField).join("")}</section>`;if(x.toto)document.getElementById("cards").innerHTML+=`<section class="card" data-match="Toto Cup"><div class="tag">Toto Cup · Fri Odds</div><div class="match">De tre øvrige spillere</div>${x.toto.map(moneyField).join("")}</section>`;document.getElementById("save").style.display=x.r.includes("FERIE")?"none":"block";document.getElementById("notice").textContent="";if(!restoreSaved_(x))restoreDraft_(x.w)}
document.getElementById("prev").onclick=()=>{pos=(pos-1+program.length)%program.length;render()};document.getElementById("next").onclick=()=>{pos=(pos+1)%program.length;render()};
function parseMoney(v){if(!v.trim())return null;const n=Number(v.trim().replace(/\s/g,"").replace(",", "."));return Number.isFinite(n)&&n>=0?n:null}
function validResult(v){return /^\d+\s*[-–]\s*\d+$/.test(v.trim())}
function validate(){const x=program[pos],inputs=[...document.getElementById("cards").querySelectorAll("input")],errors=[];inputs.forEach(el=>el.classList.remove("bad"));inputs.forEach(el=>{const isResult=el.dataset.kind==="result",value=el.value.trim();if(!value)return;const ok=isResult?validResult(value):parseMoney(value)!==null;if(!ok){el.classList.add("bad");errors.push(el)}});if(x.m.some(m=>m.includes("TBD"))){document.getElementById("notice").textContent="Pokalkampen afventer lodtrækning.";return false}if(errors.length){document.getElementById("notice").textContent="Tjek de markerede felter.";errors[0].focus();return false}const data=summary();if(!data.entries.some(function(e){return e.money!==null||e.result})){document.getElementById("notice").textContent="Indtast mindst ét beløb eller resultat før du gemmer.";return false}return true}
function restoreSaved_(x){var rows=savedEntries.filter(function(e){return Number(e.week)===Number(x.w)&&e.round===x.r});if(!rows.length)return false;document.getElementById("cards").querySelectorAll(".card[data-match]").forEach(function(card){var match=card.dataset.match;card.querySelectorAll('[data-kind="money"]').forEach(function(el){var e=rows.find(function(v){return v.match===match&&v.player===el.dataset.player});if(e&&e.money!=="")el.value=String(e.money).replace(".",",")});var re=card.querySelector('[data-kind="result"]');if(re){var e=rows.find(function(v){return v.match===match&&v.result});if(e)re.value=e.result}});return true}
function restoreDraft_(w){try{const d=JSON.parse(localStorage.getItem("oddsklubben-draft-"+w)||"null");if(!d||!Array.isArray(d.entries))return;document.getElementById("cards").querySelectorAll(".card[data-match]").forEach(card=>{const match=card.dataset.match;card.querySelectorAll('[data-kind="money"]').forEach(el=>{const e=d.entries.find(x=>x.match===match&&x.player===el.dataset.player);if(e&&e.money!==null)el.value=String(e.money).replace(".",",")});const re=card.querySelector('[data-kind="result"]');if(re){const e=d.entries.find(x=>x.match===match&&x.result);if(e)re.value=e.result}})}catch(_){}}
function summary(){const x=program[pos],entries=[];document.getElementById("cards").querySelectorAll(".card[data-match]").forEach(card=>{const match=card.dataset.match,resultEl=card.querySelector('[data-kind="result"]'),result=resultEl?resultEl.value.trim():"";card.querySelectorAll('[data-kind="money"]').forEach(el=>entries.push({match,player:el.dataset.player,money:parseMoney(el.value),result}))});return {week:x.w,round:x.r,entries}}
document.getElementById("save").onclick=()=>{if(!validate())return;const data=summary();document.getElementById("notice").innerHTML=`<div class="confirm"><strong>Klar til at gemme uge ${data.week}</strong><span>Kontrollér oplysningerne og tryk Bekræft.</span><button id="confirmSave">Bekræft og gem</button><button id="cancelSave" class="secondary">Ret oplysninger</button></div>`;document.getElementById("cancelSave").onclick=()=>document.getElementById("notice").textContent="";document.getElementById("confirmSave").onclick=()=>{localStorage.setItem("oddsklubben-draft-"+data.week,JSON.stringify(data));const btn=document.getElementById("confirmSave");btn.disabled=true;btn.textContent="Gemmer…";if(!API_URL){document.getElementById("notice").innerHTML='<div class="success">✓ Gemt som lokal kladde.<br><small>Backend er endnu ikke deployet.</small></div>';return}fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(data)}).then(function(res){return res.json()}).then(function(out){if(!out.ok)throw new Error(out.error||"Ukendt fejl");document.getElementById("notice").innerHTML=`<div class="success">✓ ${out.status==="written"?"Gemt i Google Sheet":"Test godkendt (dry-run)"}.<br><small>Uge ${data.week} · ${data.round}</small></div>`}).catch(function(err){document.getElementById("notice").innerHTML=`<div class="error">Kunne ikke gemme: ${String(err.message||err)}<br><small>Din lokale kladde er bevaret.</small></div>`})}};render();
fetch(API_URL).then(function(res){return res.json()}).then(function(out){if(out && out.ok && Array.isArray(out.program) && out.program.length){program=out.program;savedEntries=Array.isArray(out.saved)?out.saved:[];pos=initialPosition();render()}}).catch(function(){});